### ISSUE TITLE
how to know if a zone is watering?

### ISSUE THREAD

**Issue by mrose17** [boatmeme/rachio#1]
that's the question. some time ago i wanted to write a homebridge plugin that would model a IRO zone as an on/off switch, cf. option (3) in https://github.com/nfarina/homebridge/issues/452#issuecomment-269875294 and i still haven't figured out where in the API to figure out whether a zone is watering or how to turn watering on/off in a zone. have you had any luck?

thanks!

**Comment by boatmeme** [comment]
Hello. Sorry for the delayed response. I just got back to working on the project this week.

So, the way to check if a zone is watering is to get the Device's current schedule which you can fetch from this resource:

```GET /public/device/:id/current_schedule```

That will return a payload that contains a zoneId, the start, the duration, the schedule id, etc. See [https://rachio.readme.io/docs/publicdeviceidcurrent_schedule](https://rachio.readme.io/docs/publicdeviceidcurrent_schedule) for more details.

Once you have a Zone Id, you can turn watering on by calling the following resource:

```
PUT /public/zone/start

{
  id: YOUR_ZONE_ID,
  duration: INTEGER_DURATION_IN_SECONDS
}
```

Turning watering off is accomplished by calling the Device's stop watering resource. This will cancel the current schedule.

```
PUT /public/device/stop_water

{
  id: YOUR_DEVICE_ID
}
```

Hopefully that helps for your situation. Unfortunately, the API isn't particularly well-designed - at least from a RESTful perspective - but I'm going to try to obscure some of the complexities / inconsistencies through this SDK project.

Good luck!

**Comment by boatmeme** [comment]
After I merge the upcoming PR for v0.1.0, you can get the zone being currently watered with the following code:

```
... 
// initialize client, etc.
...

client.getDevice(MY_DEVICE_ID)
  .then( device => device.getActiveZone() )
  .then( activeZone => {
     // Do what you will with the zone, value is false if no zone currently active
  });


```

**Comment by mrose17** [comment]
thanks very much! i look forward to the merge and `npm publish` !!!

**Comment by mrose17** [comment]
many thanks! my goal is to make use of version 0.2.0 this week (i hope!)

**Comment by boatmeme** [comment]
You're welcome! Let me know how it goes. 

FYI - you'll probably want version 0.1.1, which is the latest published to npm. I bumped the version in master for the next release, but I'm still figuring out the whole npm module / ci / release / publish workflow. It's a learning process... 😃

**Comment by mrose17** [comment]
good point. i think you need to do one more `npm publish`

        npm ERR! notarget No compatible version found: rachio@0.2.0
        npm ERR! notarget Valid install targets:
        npm ERR! notarget 0.0.1, 0.1.0, 0.1.1
        npm ERR! notarget

(-;
